name: Build, Test, and Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Use a specific Python version matching your project's requirement
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies including dev extras
      run: |
        # Install the package itself in editable mode along with dev dependencies
        uv pip install -e .[dev]

    - name: Run tests
      run: |
        pytest

    - name: Build package
      run: |
        # Ensure build dependencies are installed if not covered by [dev]
        # uv pip install build
        uv build

    - name: Upload distribution artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        if-no-files-found: error # Fail if build didn't produce files

  publish:
    needs: test # Run only after the test job succeeds
    if: startsWith(github.ref, 'refs/tags/v') # Run only for version tags
    runs-on: ubuntu-latest

    # Specify the environment configured for Trusted Publishing
    environment: pypi

    # Grant GITHUB_TOKEN the permissions required to fetch the OIDC token
    permissions:
      id-token: write # Required for trusted publishing

    steps:
    - uses: actions/checkout@v4 # Checkout is needed again in this job

    - name: Download distribution artifact
      uses: actions/download-artifact@v4
      with:
        name: dist # Match the artifact name from the test job
        path: dist/

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Publish package to PyPI
      run: |
        uv publish